/*  randRange returns a random number between a given range nMin to nMax.
    @param int nMin - the minimum number
    @param int nMax - the maximum number
    @return a random number between nMin and nMax
*/
int randRange(int nMin, int nMax){
    return nMin + (rand() / (RAND_MAX / (nMax - nMin + 1)));
}

/*  startBattle initializes an enemy to fight then proceeds to playerTurn.
    @param player* p holds all necessary information to be passed around to other menus. 
*/
void startBattle(player* p){
    enemy e; 
    int i;

    if(p->nFloor % 5 == 0){ // let player choose an elite enemy to fight 
        chooseElite(&e, p->nFloor);
    }
    else{
        generateEnemy(&e); // instantiate a basic enemy to fight
    }

    for(i = 0; i < 3; i++){ // use up one of each sync pair for each battle.
        p->nSyncPairHeld[i] -= 1;
    }
    playerTurn(p, &e);
}

/*  generateEnemy adjusts the stats of the enemy struct to be the stats of a basic enemy on floor numbers not divisible by 5.
    will also give the enemy a randomized name. 
    @param enemy* e will receive the information randomized for a normal enemy
    Pre-condition: the player is on a floor number NOT divisible by 5.
*/
void generateEnemy(enemy* e){
    int nRandomName;
    nRandomName = randRange(0, 45); // generate a random number to choose a random element from the array strEnemyNames
    // Array of strings (list of the possible enemy names)
    char* strEnemyNames[46] = {
        "Lord Oni",
        "Hog Rider",
        "Sorc Tails",
        "Prof Azmyne",
        "Gamer Exile",
        "Trainer Rai",
        "Lechonk",
        "Crewmate",
        "Impostor",
        "Michael",
        "Trainer DIO",
        "Trainer JoJo",
        "Tarnished",
        "Trainer Fia",
        "Gideon Ofnir",
        "Sorc Rogier",
        "Goldmask",
        "Roderika",
        "Witch Ranni",
        "Wolf Blaidd",
        "Patches",
        "Dung Eater",
        "Astolfo",
        "Isshin",
        "Gyoubu Oniwa",
        "Rimuru",
        "Benimaru",
        "Guy Crimson",
        "Rain",
        "Misery",
        "Diablo",
        "Testarossa",
        "Ultima",
        "Carrera",
        "Leon",
        "Ramiris",
        "Dino",
        "Dagruel",
        "Valentine",
        "Milim Nava",
        "Veldora",
        "Velzard",
        "Velgrynd",
        "Guts",
        "Griffith",
        "Caska",
    };
    e->nEnemyRandomImage = randRange(0, 4);
    e->nEnemySyncMoveCounter = 0;
    e->nEnemyHP = 100;
    e->nEnemyType = 0;
    e->nEnemyFlinching = 0;
    e->nEnemyMaxHP = 100;
    e->nEnemyMinDMG = 10;
    e->nEnemyMaxDMG = 20;
    e->nEnemyFlinchChance = 20;
    e->strEnemyName = strEnemyNames[nRandomName];
}

/*  chooseElite lets the player choose between 
    two possible elite enemies to fight on floors divisible by 5
    @param enemy* e will receive the information generated by the function.
    @param int nFloor is used to determine which elite enemy to generate. 
    Pre-condition: the player is on a floor number divisible by 5.
*/
void chooseElite(enemy* e, int nFloor){
    char cSelect;
    int nEliteLevel = (nFloor / 5) - 1;
    char* strEliteEnemyNames[4][2] = {
        {"Will", "Karen"},
        {"Glacia", "Flint"},
        {"Grimsley", "Shauntal"},
        {"Acerola", "Siebold"}
    };

    printChooseElite(strEliteEnemyNames[nEliteLevel][0], strEliteEnemyNames[nEliteLevel][1]);
    cSelect = getche();
    printf(RESET); //reset colors

    switch(cSelect){
        case '1':
            generateElite(e, strEliteEnemyNames[nEliteLevel][0]);
            break;
        case '2':
            generateElite(e, strEliteEnemyNames[nEliteLevel][1]);
            break;
        default:
            chooseElite(e, nFloor);
            break;
    }
}

/*  generateElite initializes an enemy to fight then breaks to proceed to playerTurn.
    @param enemy* e will receive the information based on which elite enemy will be fought.
    @param char* strEliteName will be used to identify the enemy type to be generated.
*/
void generateElite(enemy* e, char* strEliteName){
    // * cant use switch for string so just chain if else using strcmp()
    // strcmp() returns 0 if the two strings are the same and 1 otherwise.
    if(
        !strcmp("Karen", strEliteName) || 
        !strcmp("Flint", strEliteName) || 
        !strcmp("Siebold", strEliteName)){
        e->nEnemyType = 1;
    }
    else if(
        !strcmp("Will", strEliteName) || 
        !strcmp("Grimsley", strEliteName)){
        e->nEnemyType = 2;
    }
    else{
        e->nEnemyType = 3;
    }

    switch(e->nEnemyType){
        case 1:
            e->nEnemyHP = 100;
            e->nEnemyMaxHP = 100;
            e->nEnemyMinDMG = 15;
            e->nEnemyMaxDMG = 30;
            e->nEnemyFlinchChance = 15;
            break;
        case 2:
            e->nEnemyHP = 150;
            e->nEnemyMaxHP = 150;
            e->nEnemyMinDMG = 15;
            e->nEnemyMaxDMG = 25;
            e->nEnemyFlinchChance = 30;
            break;
        case 3:
            e->nEnemyHP = 200;
            e->nEnemyMaxHP = 200;
            e->nEnemyMinDMG = 10;
            e->nEnemyMaxDMG = 20;
            e->nEnemyFlinchChance = 20;
            break;
    }

    e->nEnemySyncMoveCounter = 0;
    e->nEnemyRandomImage = randRange(0, 4);
    e->nEnemyFlinching = 0;
    e->strEnemyName = strEliteName;
}